name: CI

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm Install

      - name: Lint code
        run: npm run lint

      - name: Run unit tests
        run: npm test

      - name: Run Cypress tests
        run: npx cypress run || true

      - name: Build app
        run: npm run build